### ISSUE TITLE
Chaining prompts doesn't work correctly

### ISSUE THREAD

**Issue by mm-gmbd** [carlos8f/node-cli-prompt#3] opened 2015-07-22 16:40 UTC
Chaining prompts or using prompt.multi doesn't work correctly. Every time enter is pressed, the next chained prompt automatically gets called.

Even the first example works improperly:

    var prompt = require('cli-prompt');

    prompt('enter your first name: ', function (val) {
      var first = val;
      prompt('and your last name: ', function (val) {
        console.log('hi, ' + first + ' ' + val + '!');
      });
    });

    //PROGRAM START
    //Output:
    //enter your first name: max //ENTER KEYPRESS HERE
    //and your last name: hi, max !
    //PROGRAM END

Running node version v0.10.38 (in Windows command prompt)
cli-prompt version v0.4.1

**Comment by carlos8f** [comment] 2015-07-22 18:12
I'm unable to reproduce, but I run OSX and deploy to Ubuntu. Must be a problem with Windows (and I don't target Windows generally). Will accept a patch if you can get it working.

**Comment by mm-gmbd** [comment] 2015-07-23 13:05
It seems like for some reason a single enter keypress is propagating to the next waiting prompt. I'll fork and see if I can get it working.

**Comment by carlos8f** [comment] 2015-07-23 17:50
Thanks for the work on this, but I can't accept this patch, it breaks OSX and Linux support. The mappings are such:

```
\r = return
\n = enter
```

so by listening to a carriage return only, you're listening to a Windows-only thing. To truly fix it, you'd have to listen for a sequence (`\r\n` on Windows, `\n` on other platforms) and I don't have the time to do that.

I would suggest using a different module which has Windows support, unfortunately :(

**Comment by mm-gmbd** [comment] 2015-07-23 20:08
Understood, I've done a little more research and now know more about the differences between Windows and other platforms (of course there is a difference on Windows :P). I've submitted a separate patch that may work across all systems (I've tested on windows, and it should work on Mac/Unix).

**Comment by carlos8f** [comment] 2015-07-23 23:38
Last last version works. I merged it, and I added a test (which proves that it responds correctly to Windows `\r\n`) and published it as cli-prompt@0.4.2 .

Thanks and Cheers: :beers:

**Closed by carlos8f** 2015-07-23 23:38 UTC

**Comment by mm-gmbd** [comment] 2015-07-24 10:09
Glad it worked - cheers!
